### ISSUE TITLE
ImportError: No module named index.text.lexicon

### ISSUE THREAD

**Issue by andreaortuno** [datamade/dedupe#410]
after installing dedupe in a Mac OS X and following the developers set up guide I get the following error when I try to run  cvs_example.py . I already tried pip install zope.index.
```
dedupe-examples-master $USER $ python csv_example/csv_example.py 
/Users/aortuno/dedupe/dedupe/backport.py:17: UserWarning: NumPy linked against 'Accelerate.framework'. Multiprocessing will be disabled. http://mail.scipy.org/pipermail/numpy-discussion/2012-August/063589.html
  warnings.warn("NumPy linked against 'Accelerate.framework'. "
Traceback (most recent call last):
  File "csv_example/csv_example.py", line 26, in <module>
    import dedupe
  File "/Users/$USER/dedupe/dedupe/__init__.py", line 6, in <module>
    from dedupe._init import *
  File "/Users/$USER/dedupe/dedupe/_init.py", line 1, in <module>
    from dedupe.api import StaticDedupe, Dedupe
  File "/Users/$USER/dedupe/dedupe/api.py", line 26, in <module>
    import dedupe.training as training
  File "/Users/$USER/dedupe/dedupe/training.py", line 10, in <module>
    from . import blocking, predicates, core, index, backport
  File "/Users/$USER/dedupe/dedupe/predicates.py", line 11, in <module>
    import dedupe.tfidf as tfidf
  File "/Users/$USER/dedupe/dedupe/tfidf.py", line 4, in <module>
    from .index import CanopyIndex
  File "/Users/$USER/dedupe/dedupe/index.py", line 3, in <module>
    from zope.index.text.lexicon import Lexicon
ImportError: No module named index.text.lexicon
```
does anyone know why this is happening?

**Comment by fgregg** [comment]
Argh! This mysterious issue is like #268 

Try doing `pip install zope.index`

**Comment by andreaortuno** [comment]
I tried `pip install zope.index` and it didn't work either. For some reason pip doesn't install it in the right folder. I just ended up coping the index folder from zope.index into the /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zope folder.
