### ISSUE TITLE
ZeroDivisionError: float division

### ISSUE THREAD

**Issue by kshishir** [datamade/dedupe#442]
I just updated dedupe using pip in my linux environment and I started getting this error in Active Learning class.
The error is thrown when it is trying to calculate fieldDistance.
I compared the code to the previous version and there was a slight change in method.

Any idea why I am getting this error? 

Traceback (most recent call last):
  File "er_dedupe.py", line 149, in <module>
    deduper.sample(data_d, 700)
  File "/root/anaconda/lib/python2.7/site-packages/dedupe/api.py", line 931, in sample
    self._loadSample(data_sample)
  File "/root/anaconda/lib/python2.7/site-packages/dedupe/api.py", line 873, in _loadSample
    self.num_cores)
  File "/root/anaconda/lib/python2.7/site-packages/dedupe/training.py", line 53, in __init__
    2))
  File "/root/anaconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/root/anaconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ZeroDivisionError: float division

**Comment by primoz-k** [comment]
Check if your data in any of the field is empty string. It should be None instead of empty strings.

**Comment by kshishir** [comment]
There are no null values. It was working fine before I updated the dedupe.

**Comment by fgregg** [comment]
@primoz-k is probably right. We changed how we handled empty strings.

**Comment by kshishir** [comment]
There are no empty strings in the input file.

**Comment by fgregg** [comment]
not giving us a lot to work with, @kshishir 

you can always go to an earlier version of dedupe.

**Comment by kshishir** [comment]
I am trying to debug it on my end as well. 
I changed to version 1.2.2 and I am still getting the error.
I had updated anaconda before updating dedupe so I am going to uninstall the latest version of anaconda and try again.

**Comment by kshishir** [comment]
I uninstalled current version of anaconda and installed an older version:
Now I have: Python 2.7.10 |Anaconda 2.3.0 (64-bit)
and it started working with the latest version of dedupe.

**Comment by urbaneBayes** [comment]
hi there, this has reared its head for me. seems to be tied to affinegap. Using dedupe 1.7.5 and Python 3.5.3 on a Ubuntu 16 VM . I defined 6 variables, one of which is Price and another Exact (rest String). Price is a positive float. Adapted the pgsql example with the intent of using the Exact variable to record match instead of deduplicate.

`Traceback (most recent call last):
  File "mat1.py", line 119, in <module>
    deduper.sample(temp_d, 75000)
  File "/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/api.py", line 802, in sample
    self.active_learner.sample_combo(data, blocked_proportion, sample_size)
  File "/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/labeler.py", line 148, in sample_combo
    super(RLRLearner, self).sample_combo(*args)
  File "/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/labeler.py", line 49, in sample_combo
    self.distances = self.transform(self.candidates)
  File "/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/labeler.py", line 89, in transform
    return self.data_model.distances(pairs)
  File "/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/datamodel.py", line 82, in distances
    record_2[field])
  File "affinegap/affinegap.pyx", line 115, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1991)
  File "affinegap/affinegap.pyx", line 134, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1824)
ZeroDivisionError: float division`

Tried slapping from __future__ import division at the top as suggested [here](https://stackoverflow.com/questions/7479292/get-zerodivisionerror-float-division-in-python). That produced a slightly different error. I'm going to try and run it in Python 2.. I'll report back soon and would love any help! 

`/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/sampling.py:39: UserWarning: 37500 b
locked samples were requested, but only able to sample 37499
  % (sample_size, len(blocked_sample)))
Traceback (most recent call last):
  File "mat2.py", line 120, in <module>
    deduper.sample(temp_d, 75000)
  File "/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/api.py", line 802, in sample
    self.active_learner.sample_combo(data, blocked_proportion, sample_size)
  File "/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/labeler.py", line 148, in sa
mple_combo
    super(RLRLearner, self).sample_combo(*args)
  File "/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/labeler.py", line 49, in sam
ple_combo
    self.distances = self.transform(self.candidates)
  File "/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/labeler.py", line 89, in tra
nsform
    return self.data_model.distances(pairs)
  File "/home/[user]/environments/molten/lib/python3.5/site-packages/dedupe/datamodel.py", line 82, in d
istances
    record_2[field])
  File "affinegap/affinegap.pyx", line 115, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap
.c:1991)
  File "affinegap/affinegap.pyx", line 134, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap
.c:1824)
ZeroDivisionError: float division`

**Comment by urbaneBayes** [comment]
doh. I had blank spaces... still, the UserWarning: 37500 blocked samples were requested, but only able to sample 37499 error is surprising.

**Comment by lucianocheng** [comment]
Just hit this error myself while passing in `markPairs` to a deduper (`deduper.markPairs()`)

Just a heads up that even if you pass in different `markPairs`, the original `markPairs` causing the error are still in the deduper.  You either need to flush them or create another deduper instance to get past this error.

**Comment by Sharmilinag** [comment]
I have also faced the same issue as ZeroDivisionError: division by zero. I have tried with "has missing" and replacing empty column with "null" values. But still the error is occurring. Please help me out.
