### ISSUE TITLE
Getting error on dedupe.canonicalize(cluster_d) call for a datetime field

### ISSUE THREAD

**Issue by mdford** [datamade/dedupe#445]
I am getting an error on a dedupe.canonicalize(cluster_d) call.  It is on a datetime field in my record.  (This is not a field I am using for comparison).  

``
Traceback (most recent call last):
  File "/home/mford/apps/pycharm-5.0.4/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/mford/apps/pycharm-5.0.4/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/home/mford/projects/thorlo/database/mssql/thorlo.py", line 104, in <module>
    canonical_rep = dedupe.canonicalize(cluster_d)
  File "/home/mford/.virtualenvs/mssql/local/lib/python2.7/site-packages/dedupe/convenience.py", line 195, in canonicalize
    return getCanonicalRep(record_cluster)
  File "/home/mford/.virtualenvs/mssql/local/lib/python2.7/site-packages/canonicalize/centroid.py", line 56, in getCanonicalRep
    canonical_rep[key] = getCentroid(key_values, comparator)
  File "/home/mford/.virtualenvs/mssql/local/lib/python2.7/site-packages/canonicalize/centroid.py", line 18, in getCentroid
    distance = comparator(attribute_variants[i], attribute_variants[j])
TypeError: Argument 'string1' has incorrect type (expected basestring, got datetime.datetime)
``
Is there something I need to do for datetime fields?  I know you can specify custom comparators but this is not a field I want to consider in my deduping/matching.

Thanks!

**Comment by fgregg** [comment]
Relate to https://github.com/datamade/canonicalize/issues/1

Our canonicalize function is actually pretty simplistic. It can only handle strings. It can, and should be extended to handle different comparisons for different datatypes. 

In the meantime, you can get around the error by casting your datetime to a string.
