### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by samirfor** [datamade/dedupe#512]
Files for reproduction: [dedupe.zip](https://github.com/datamade/dedupe-examples/files/704396/dedupe.zip)

```
$ docker run -it --rm -v $PWD:/data -w /data samirfor/csvdedupe-docker --config_file config.json ticmix.csv

INFO:root:imported 12 rows
INFO:root:using fields: ['titulo', 'data', 'hora', 'cidade_estado']
INFO:root:taking a sample of 150000 possible pairs
/usr/local/lib/python3.5/site-packages/dedupe/sampling.py:39: UserWarning: 75000 blocked samples were requested, but only able to sample 55
  % (sample_size, len(blocked_sample)))
INFO:root:reading labeled examples from training.json
INFO:dedupe.api:reading training from file
INFO:root:starting active labeling...

INFO:dedupe.training:Final predicate set:
INFO:dedupe.training:(SimplePredicate: (fingerprint, titulo), TfidfNGramCanopyPredicate: (0.2, data))
INFO:root:caching training result set to file learned_settings
INFO:root:blocking...
INFO:root:finding a good threshold with a recall_weight of 2
INFO:dedupe.blocking:Canopy: TfidfNGramCanopyPredicate: (0.2, data)
Traceback (most recent call last):
  File "/usr/local/bin/csvdedupe", line 9, in <module>
    load_entry_point('csvdedupe==0.1.14', 'console_scripts', 'csvdedupe')()
  File "/usr/local/lib/python3.5/site-packages/csvdedupe-0.1.14-py3.5.egg/csvdedupe/csvdedupe.py", line 180, in launch_new_instance
  File "/usr/local/lib/python3.5/site-packages/csvdedupe-0.1.14-py3.5.egg/csvdedupe/csvdedupe.py", line 127, in main
  File "/usr/local/lib/python3.5/site-packages/dedupe/api.py", line 235, in threshold
    return self.thresholdBlocks(blocked_pairs, recall_weight)
  File "/usr/local/lib/python3.5/site-packages/dedupe/api.py", line 76, in thresholdBlocks
    recall = expected_dupes / expected_dupes[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0
```

```
/data # pip3 list
affinegap (1.10)
affinegap (1.10)
BTrees (4.3.2)
canonicalize (1.3)
categorical-distance (1.9)
csvdedupe (0.1.14)
dedupe (1.6.0)
dedupe-hcluster (0.3.2)
DoubleMetaphone (0.1)
fastcluster (1.1.22)
future (0.16.0)
haversine (0.4.5)
highered (0.2.1)
Levenshtein-search (1.4.2)
nose (1.3.7)
numpy (1.11.3)
persistent (4.2.2)
pexpect (4.2.1)
pip (9.0.1)
ptyprocess (0.5.1)
pyhacrf-datamade (0.2.0)
PyLBFGS (0.2.0.3)
rlr (2.4)
setuptools (20.10.1)
simplecosine (1.1)
simplejson (3.10.0)
six (1.10.0)
zope.index (4.2.0)
zope.interface (4.3.3)
/data # python
Python 3.5.2 (default, Dec 27 2016, 21:33:11) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> sys.maxsize
9223372036854775807
```

**Comment by fgregg** [comment]
The underlying problem is that there are no duplicates in tixmix.csv. But we will add a better error message.

**Comment by fgregg** [comment]
Closed by https://github.com/datamade/dedupe/commit/e09cbdecdef32f8796dd70068fdc2c1081572e36
