### ISSUE TITLE
30k rows causes KeyError. core.randomPairs generate invalid keys

### ISSUE THREAD

**Issue by micbster** [datamade/dedupe#519]
For large dataset, a KeyError is generated at line 46 of Labeler.py. The reason appears that the core.randomPairs call at line 41 of Labeler.py generates keys at are out of bound of the unique dataset. The dataset I was using had not ID set and was 30k rows.

I modified randomPairs to generate random pair using numpy.random.random_integer(0, lengthOfData, sample_size) for each of the item in the returned tupled; this worked.

csvdedupe FakeNames.csv  --field_names "Number" "Gender" "Name
Set" "Title" "GivenName" "MiddleInitial" "Surname" "StreetAddress" "City" "State" "StateFull" "ZipCode" "Country" "CountryFull"  --output_fi
le output.csv
INFO:root:imported 50000 rows
INFO:root:using fields: ['Number', 'Gender', 'NameSet', 'Title', 'GivenName', 'MiddleInitial', 'Surname', 'StreetAddress', 'City', 'State',
'StateFull', 'ZipCode', 'Country', 'CountryFull']
INFO:root:taking a sample of 1500 possible pairs
Traceback (most recent call last):
  File "C:\Users\abc123\csvdedupe\Scripts\csvdedupe-script.py", line 11, in <module>
    load_entry_point('csvdedupe==0.1.14', 'console_scripts', 'csvdedupe')()
  File "build\bdist.win-amd64\egg\csvdedupe\csvdedupe.py", line 180, in launch_new_instance
  File "build\bdist.win-amd64\egg\csvdedupe\csvdedupe.py", line 107, in main
  File "C:\Users\abc123\csvdedupe\lib\site-packages\dedupe\api.py", line 790, in sample
    self.active_learner.sample_combo(data, blocked_proportion, sample_size)
  File "C:\Users\abc123\csvdedupe\lib\site-packages\dedupe\labeler.py", line 148, in sample_combo
    super(RLRLearner, self).sample_combo(*args)
  File "C:\Users\abc123\csvdedupe\lib\site-packages\dedupe\labeler.py", line 47, in sample_combo
    in blocked_sample_keys | random_sample_keys]
KeyError: 4294962435
[FakeNames.zip](https://github.com/datamade/dedupe/files/765466/FakeNames.zip)

**Comment by micbster** [comment]
My fix

    i = random.sample(random(n_records), sample_size).astype('uint')
    j = random.sample(random(n_records), sample_size).astype('uint')

**Comment by fgregg** [comment]
could you also post your OS, python version, and 

```python
print(sys.maxint)
```

**Comment by micbster** [comment]
2147483647
Win 7 Ent 64bit
Python 2.7.13 mounted in virtualenv

**Comment by fgregg** [comment]
can you try

```
    i = numpy.floor((-b - numpy.sqrt(8 * (n - random_pairs) + 1)) / 2).astype('uint')
    j = numpy.rint(random_pairs + i * (b + i + 2) / 2 + 1).astype('uint')
```

**Comment by fgregg** [comment]
can you try this commit https://github.com/datamade/dedupe/commit/6528b75605dc5e3ddccc6f8054ba2f314f5a5194

**Comment by fgregg** [comment]
ping @micbster

**Comment by micbster** [comment]
yes, sorry about that, will do

**Comment by fgregg** [comment]
ping @micbster

**Comment by micbster** [comment]
yes, it works thanks!
Do you have information on the random hashing technique you are using?

**Comment by fgregg** [comment]
Great! https://stackoverflow.com/questions/5323818/condensed-matrix-function-to-find-pairs/14839010#14839010

**Comment by bdanielthorpe** [comment]
Hello, apologies if this is the wrong place to post this but I'm having the same issue on Python 3.6.8, Windows 10.

Traceback (most recent call last):
  File "d:/Documents/golden_record/platform/platform_dedupe_personcontact.py", line 128, in <module>
    deduper.sample(temp_d)
  File "C:\Users\Ben\envs\standardenv\lib\site-packages\dedupe\api.py", line 842, in sample
    index_include=examples)
  File "C:\Users\Ben\envs\standardenv\lib\site-packages\dedupe\labeler.py", line 405, in __init__
    self.candidates = super().sample(data, blocked_proportion, sample_size)
  File "C:\Users\Ben\envs\standardenv\lib\site-packages\dedupe\labeler.py", line 56, in sample
    in blocked_sample_keys | random_sample_keys]
  File "C:\Users\Ben\envs\standardenv\lib\site-packages\dedupe\labeler.py", line 55, in <listcomp>
    for k1, k2
KeyError: 2147557443

Any help much appreciated.
