### ISSUE TITLE
ValueError: Records do not line up with data model. The field 'name' is in data_model but not in a record

### ISSUE THREAD

**Issue by 583143** [datamade/dedupe#545]
I followed the tutorial and tried to convert the code for Hive from MySQL. But I get the following error. I could populate all tables and stuck here badly

>>> deduper.sample(temp_d, 10000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hdusr/Envs/dedupe-examples/lib/python2.7/site-packages/dedupe/api.py", line 781, in sample
    self._checkData(data)
  File "/home/hdusr/Envs/dedupe-examples/lib/python2.7/site-packages/dedupe/api.py", line 801, in _checkData
    self.data_model.check(next(iter(viewvalues(data))))
  File "/home/hdusr/Envs/dedupe-examples/lib/python2.7/site-packages/dedupe/datamodel.py", line 122, in check
    "in a record" % field)

Any help please !

Thnx,
Az

**Comment by fgregg** [comment]
This is saying that you don't have the key of 'name in your record. Can't really say more than that with what you have reported.
